[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html